### ISSUE TITLE
4 Path Tracks does not work

### ISSUE THREAD

**Issue by KujawskiSzymon** [pjsavola/formulad#3]

**Comment by pjsavola** [comment]
Could you provide more details what you tried to do?

**Comment by KujawskiSzymon** [comment]
Hi, sorry for delay
Tried Daytona with mix 4/3 path - looks like I there is a trick with block node to make it work but there is lack of documentation
Could you provide how to use Block node? 
![do issue](https://github.com/pjsavola/formulad/assets/42217160/75ee5895-ab1c-4d64-864e-0f4a3b823054)
I added photo where the mix is present

**Comment by pjsavola** [comment]
Yeah, unfortunately documentation is very lacking, sorry about that. If I remember correctly the idea of block nodes is that it virtually continues the lane without actually allowing any movement through the virtual lane. This way the game can understand where extra lane begins and ends, because otherwise it tries to automatically calculate lanes.

**Comment by KujawskiSzymon** [comment]
Thanks, I was able to use it properly this time, and made it work
